Delete uuids trashed more than 1 year ago
serlo/db-migrations pull request #164
Opened 2023-10-05 15:55 UTC by AndreasHuber

2023-10-05 15:56 UTC, AndreasHuber commented on src/20231005150000-delete-uuids-trashed-more-than-1-year-ago.ts
> +      FROM event_log, uuid, entity
This for now is for entities only and I guess we want also for comments, terms,...

2023-10-05 19:55 UTC, kulla requested changes
First feedback :smile:

2023-10-05 19:55 UTC, kulla commented on package.json
> +    "date-fns": "^2.30.0",
Add them to dev dependencies -> since they will be bundled into `migrations/20231005150000-delete-uuids-trashed-more-than-1-year-ago.js`

2023-10-05 19:55 UTC, kulla commented on package.json
> +    "mysql": "docker-compose exec mysql serlo-mysql",
`docker-compose` is deprecated, see https://docs.docker.com/compose/migrate/ -> Please update your `docker`

2023-10-06 09:58 UTC, hugotiburtino commented on src/20231005150000-delete-uuids-trashed-more-than-1-year-ago.ts
> +      FROM event_log, uuid, entity
Altough I think the request is really related to entities (because only they are in the trash bin) we could strive to delete also the other ones
```sql
> select discriminator, count(discriminator) from uuid where trashed = 1 group by discriminator;
+----------------+----------------------+
| discriminator  | count(discriminator) |
+----------------+----------------------+
| blogPost       |                    6 |
| comment        |                  727 |
| entity         |                 2459 |
| entityRevision |                 1474 |
| pageRevision   |                    2 |
| taxonomyTerm   |                  920 |
+----------------+----------------------+

```

2023-10-06 09:58 UTC, hugotiburtino commented on src/20231005150000-delete-uuids-trashed-more-than-1-year-ago.ts
> +      AND uuid.trashed = 1
Removing the discriminator is a step, but isn't enough.

```sql
> SELECT count(uuid_id)   
      FROM event_log, uuid, entity
       WHERE uuid.id = event_log.uuid_id
       AND event_log.date < "2022-10-06" 
       AND entity.id = event_log.uuid_id
       AND event_log.event_id = 10
       AND uuid.trashed = 1 and uuid.discriminator = 'entity' ;
+----------------+
| count(uuid_id) |
+----------------+
|           2220 |
+----------------+
1 row in set (0.00 sec)

> SELECT count(uuid_id)
       FROM event_log, uuid, entity
       WHERE uuid.id = event_log.uuid_id
       AND event_log.date < "2022-10-06"
       AND entity.id = event_log.uuid_id
       AND event_log.event_id = 10
       AND uuid.trashed = 1;
+----------------+
| count(uuid_id) |
+----------------+
|           2220 |
+----------------+
```

2023-10-06 09:59 UTC, hugotiburtino commented on src/20231005150000-delete-uuids-trashed-more-than-1-year-ago.ts
> +      AND uuid.trashed = 1
sorry, my bad

2023-10-06 10:02 UTC, hugotiburtino approved these changes

2023-10-06 10:12 UTC, hugotiburtino commented
Before merging, please update version at `package.json`

2023-10-06 10:57 UTC, elbotho approved these changes
nice, thank you.
Can I get some example uuids or a list of uuids that this would delete?

2023-10-06 10:57 UTC, elbotho commented on src/20231005150000-delete-uuids-trashed-more-than-1-year-ago.ts
> +        `)
so we keep the events, correct?

2023-10-06 11:51 UTC, hugotiburtino commented
Please just give some thought on why the trashed entity revisions aren't deleted and how to delete them.

Before the migration:
```sql
+----------------+----------------------+
| discriminator  | count(discriminator) |
+----------------+----------------------+
| blogPost       |                    6 |
| comment        |                  727 |
| entity         |                 2459 |
| entityRevision |                 1474 |
| pageRevision   |                    2 |
| taxonomyTerm   |                  920 |
+----------------+----------------------+

```
After
```sql
> select discriminator, count(discriminator) from uuid where trashed = 1 group by discriminator;
+----------------+----------------------+
| discriminator  | count(discriminator) |
+----------------+----------------------+
| comment        |                   70 |
| entity         |                  274 |
| entityRevision |                 1474 |
| taxonomyTerm   |                   30 |
+----------------+----------------------+

```

2023-10-06 11:52 UTC, AndreasHuber commented on src/20231005150000-delete-uuids-trashed-more-than-1-year-ago.ts
> +        `)
No, I think a DELETE in the uuid table also cascades down to the event_log table. I am not sure how to query the DELETE cascade, though. Maybe we want to look it up.

2023-10-06 11:54 UTC, hugotiburtino commented
> how to delete them [trashed entity revisions].

Indeed, in that case, we could just use the `date` column at `entity_revision` table

2023-10-06 11:57 UTC, AndreasHuber commented on src/20231005150000-delete-uuids-trashed-more-than-1-year-ago.ts
> +        `)
```
mysql> SELECT * FROM information_schema.REFERENTIAL_CONSTRAINTS
    -> ;
+--------------------+-------------------+---------------------------------------------------+---------------------------+--------------------------+------------------------+--------------+-------------+-------------+---------------------------+---------------------------+
| CONSTRAINT_CATALOG | CONSTRAINT_SCHEMA | CONSTRAINT_NAME                                   | UNIQUE_CONSTRAINT_CATALOG | UNIQUE_CONSTRAINT_SCHEMA | UNIQUE_CONSTRAINT_NAME | MATCH_OPTION | UPDATE_RULE | DELETE_RULE | TABLE_NAME                | REFERENCED_TABLE_NAME     |
+--------------------+-------------------+---------------------------------------------------+---------------------------+--------------------------+------------------------+--------------+-------------+-------------+---------------------------+---------------------------+
```
This might be the line of interest:
```
| def                | serlo             | fk_event_log_uuid1                                | def                       | serlo                    | PRIMARY                | NONE         | CASCADE     | CASCADE     | event_log                 | uuid                      |
```

2023-10-06 12:07 UTC, AndreasHuber commented on src/20231005150000-delete-uuids-trashed-more-than-1-year-ago.ts
> +        `)
I am not sure if am interpreting this correctly. Would be great if someone else can confirm @elbotho @kulla @hugotiburtino.

2023-10-06 13:22 UTC, hugotiburtino commented on src/20231005150000-delete-uuids-trashed-more-than-1-year-ago.ts
> +        `)
> I am not sure if am interpreting this correctly.

Yes,  you are. The foreing key constrait deletes the event log automaticaly by cascading.


```sql
mysql> show create table event_log;
+-----------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table     | Create Table                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
+-----------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| event_log | CREATE TABLE `event_log` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `actor_id` bigint NOT NULL,
  `event_id` int NOT NULL,
  `uuid_id` bigint NOT NULL,
  `instance_id` int NOT NULL,
  `date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_event_fired_event1_idx` (`event_id`),
  KEY `fk_event_log_uuid1_idx` (`uuid_id`),
  KEY `fk_event_log_language1_idx` (`instance_id`),
  KEY `fk_event_log_user1_idx` (`actor_id`),
  CONSTRAINT `fk_event_fired_event1` FOREIGN KEY (`event_id`) REFERENCES `event` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_event_log_language1` FOREIGN KEY (`instance_id`) REFERENCES `instance` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_event_log_user1` FOREIGN KEY (`actor_id`) REFERENCES `user` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_event_log_uuid1` FOREIGN KEY (`uuid_id`) REFERENCES `uuid` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=538715 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci |
+-----------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

```

2023-10-06 16:00 UTC, hugotiburtino approved these changes

2023-10-06 16:08 UTC, merged