chore: Small changes to redis + mysql scripts in package.json
serlo/db-migrations pull request #289
Opened 2024-02-29 10:46 UTC by kulla

2024-03-05 15:10 UTC, kulla commented
@AndreasHuber @hugotiburtino What do you think about this PR?

2024-03-05 15:47 UTC, AndreasHuber approved these changes

2024-03-05 16:16 UTC, hugotiburtino requested changes

2024-03-05 16:16 UTC, hugotiburtino commented on package.json
> +    "mysql:cli": "docker compose exec mysql serlo-mysql",
I can't remember why, but back then it was necessary to split between a script for ci and another for the local development. But if it is now outdated and both script do the same same, we can remove mysql:cli/ci and use just one.

```suggestion
    "mysql": "docker compose exec mysql serlo-mysql",
```
Of course, everything else would have to be changed to `yarn mysql`

2024-03-09 12:57 UTC, kulla commented on package.json
> +    "mysql:cli": "docker compose exec mysql serlo-mysql",
I deleted all `:cli` versions of the command since they aren't needed any more -> Ready for review

2024-03-10 13:59 UTC, hugotiburtino approved these changes

2024-03-11 16:53 UTC, merged