chore: archive migrations 2023 or older and test if all migrations ran
serlo/db-migrations pull request #296
Opened 2024-03-04 14:25 UTC by hejtful

resolves https://github.com/serlo/db-migrations/issues/287
resolves https://github.com/serlo/db-migrations/issues/292

2024-03-04 16:41 UTC, kulla requested changes

2024-03-04 16:41 UTC, kulla commented on .github/actions/test-migrations/action.yml
> +        chmod +x ./scripts/check_all_migrations_run.sh
When you run `chmod +x ./scripts/check_all_migrations_run.sh` locally you should be able to push this change to the git repo.

2024-03-04 16:41 UTC, kulla commented on src/utils/edtr-io.ts
> -
Can you leave them here -> We will need this in the future...

2024-03-04 16:42 UTC, kulla commented
@hejtful Can you run the archived db-migrations in https://github.com/serlo/serlo-mysql-database?tab=readme-ov-file#change-db-via-migrations? -> They might change the DB structure which should be reflected here...

2024-03-04 17:13 UTC, hejtful commented on src/utils/edtr-io.ts
> -
Sure, good point. I opened an issue to rename edtr-io to serlo-editor, though: https://github.com/serlo/db-migrations/issues/298

2024-03-04 17:39 UTC, hejtful commented
@kulla I thought that the point of archiving the migrations was to prevent them from being run. I'm not sure what you want me to do now. Should I somehow run the archived migrations from this (`chore/archive-migrations-2023-or-older`) branch? Or do you want me to run them from the `main` branch? And what is the result that I'm aiming for? If the DB structure is unchanged, then the migrations can safely be archived?

2024-03-05 15:08 UTC, kulla approved these changes
@hejtful :heart:

2024-03-05 15:13 UTC, merged