feat: Add AI generated metadescription for metadata entities
serlo/db-migrations pull request #314
Opened 2024-03-21 08:58 UTC by hugotiburtino

Many entities that are queried in the metadata endpoint haven't any meta description (see [here](https://github.com/serlo/evaluations/blob/main/src/2023/2023-05-09%20Metadata-Entities%20ohne%20Description.ipynb)).
Therefore, they lack also a description for SEO. 
Generating metadescription through AI and saving in the database is the most sustainable way of solving this problem.

2024-03-25 21:51 UTC, kulla requested changes

2024-03-25 21:51 UTC, kulla commented on src/20240320150100-add-description-for-content-without-one.ts
> +      slackLogger.logEvent(`Revision ${revision.revisionId} NO DESCRIPTION`, {
First Argument in `logEvent` should be an event type like `"omitDescription"` so that we can more easily fetch for them

2024-03-25 21:51 UTC, kulla commented on src/20240320150100-add-description-for-content-without-one.ts
> +      description: `${description} [KI generiert]`,
```suggestion
      description: `${description}`,
```

Good thing to store this information => It is better to store it inside another paratemer in `entity_revision_field`, maybe `meta_description_source`, set to `"ai-generated"`?

2024-03-25 21:51 UTC, kulla commented on src/20240320150100-add-description-for-content-without-one.ts
> +    await createDescriptionWhereMissing(db, openAIClient, slackLogger)
Those two function should be mergeable

2024-03-25 21:51 UTC, kulla commented on src/20240320150100-add-description-for-content-without-one.ts
> +    await db.runSql(
For running inside the Docker container we will need a batch script

2024-03-25 21:53 UTC, kulla commented
>  Do we want to remove cache from entities? (Unnecessary for metadata endpoint, but good for SEO)

No, not needed :smile:

2024-03-25 21:55 UTC, kulla commented on src/20240320150100-add-description-for-content-without-one.ts
> +    await db.runSql(
Reason: I already run into a bug that the memory in the docker container is not enough when I updated content string and thus needed to load them into memory, you can use something as in https://github.com/serlo/db-migrations/blob/main/src/utils/create-migration.ts#L127-L174

2024-03-25 21:57 UTC, kulla commented on src/20240320150100-add-description-for-content-without-one.ts
> +    await createDescriptionWhereMissing(db, openAIClient, slackLogger)
Done in https://github.com/serlo/db-migrations/pull/314/commits/d207002700004868a8d9b9f6ecdb233fd4978a95 => The trick is to have a left join with `entity_revision_field` again for the description. This is null when there is no description and set in case there is a description (which can then be checked whether it is empty)

I haven't tested the code. Can you check it please + bug fix it when necessary?

2024-03-25 21:58 UTC, kulla commented on src/20240320150100-add-description-for-content-without-one.ts
> +      slackLogger.logEvent(`Revision ${revision.revisionId} NO DESCRIPTION`, {
Done in https://github.com/serlo/db-migrations/pull/314/commits/cec819ba513837038168e0668610b171fbf755b1

2024-03-25 21:58 UTC, kulla commented on package.json
> +    "openai": "^4.29.2"
done in https://github.com/serlo/db-migrations/pull/314/commits/49d27f4e9d7f2e278bf50b77098bc89de2780041

2024-03-25 22:01 UTC, kulla commented on src/20240320150100-add-description-for-content-without-one.ts
> +      description: `${description} [KI generiert]`,
(I wouldn't put it into the description, since we would then need to strip it in Metadata API + Frontend)

2024-03-25 22:02 UTC, kulla commented
@AndreasHuber @hugotiburtino I see the following todos:

- [ ] Add the description in batches, see https://github.com/serlo/db-migrations/pull/314/files/5864d0c84785feb2ec979a50a0a37f5ac0bda925#diff-eb91645333eee3e46f55a0d3e588fe18185e1cd4c9339a70fc4f4713ebb7d6ca
- [ ] Add a field `metadata_description_source` or `is_description_ai_generated`, see https://github.com/serlo/db-migrations/pull/314/files/5864d0c84785feb2ec979a50a0a37f5ac0bda925#diff-eb91645333eee3e46f55a0d3e588fe18185e1cd4c9339a70fc4f4713ebb7d6ca
- [ ] Reduce the script to the first 100 articles so that we can test it in `staging`

2024-03-26 11:38 UTC, hugotiburtino commented on src/20240320150100-add-description-for-content-without-one.ts
> +    await createDescriptionWhereMissing(db, openAIClient, slackLogger)
Indeed there were some ambiguous things, that were fixed in [f60fefe](https://github.com/serlo/db-migrations/pull/314/commits/f60fefefbdecf481aafe92be4d301af89b874e54).
There is one annoying thing though: if we sum the result of the two previous queries and compare with the result of the new one, we have now 8 entity_revision_field ids less. @kulla If you can identify the reason, that would be great, but I think we can just go on and ignore these 8 ones.

2024-03-26 16:21 UTC, kulla commented on src/20240320150100-add-description-for-content-without-one.ts
> +    await createDescriptionWhereMissing(db, openAIClient, slackLogger)
> If you can identify the reason, that would be great, but I think we can just go on and ignore these 8 ones.

Yep, this can be ignored

2024-03-26 16:42 UTC, kulla submitted a review, later dismissed

2024-03-26 16:42 UTC, kulla commented on src/20240326092500-add-column-ai-generated-into-entity-revision-field.ts
> +    ALTER TABLE entity_revision_field
I would have done:

```
INSERT INTO entity_revision_field (field, value)
("meta_description_is_ai_generated", "true")
```

2024-03-26 16:45 UTC, hugotiburtino commented on src/20240326092500-add-column-ai-generated-into-entity-revision-field.ts
> +    ALTER TABLE entity_revision_field
Don't we have other fields that can be generated by ai? Like content of exercises? I think keeping it general is good enough and we can make a `where field = 'meta_description'` if necessary

2024-03-26 17:19 UTC, kulla commented on src/20240326092500-add-column-ai-generated-into-entity-revision-field.ts
> +    ALTER TABLE entity_revision_field
> Don't we have other fields that can be generated by ai?

Do we have it already? If not: https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it

2024-03-27 10:16 UTC, hugotiburtino commented on src/20240326092500-add-column-ai-generated-into-entity-revision-field.ts
> +    ALTER TABLE entity_revision_field
alright, addressed in daff9f7

2024-04-09 08:04 UTC, hugotiburtino commented on src/20240326150100-add-description-for-content-without-one.ts
> +        entity.current_revision_id
@AndreasHuber 
```suggestion
        entity.id as entityId
```

2024-04-09 08:04 UTC, hugotiburtino commented on src/20240326150100-add-description-for-content-without-one.ts
> +function deleteCacheKeys(keys: string[]) {
@AndreasHuber 
No blocker, but it is better to use the following util object
https://github.com/serlo/db-migrations/blob/84227e5248b3e5ae9ac8753a63a1924877ae99eb/src/utils/api-cache.ts

2024-04-09 09:06 UTC, AndreasHuber commented on src/20240326150100-add-description-for-content-without-one.ts
> +function deleteCacheKeys(keys: string[]) {
Can you explain why it is better? It looks like an abstraction layer to me that won't make the code simpler.

2024-04-09 11:15 UTC, hugotiburtino commented on src/20240326150100-add-description-for-content-without-one.ts
> +function deleteCacheKeys(keys: string[]) {
It is not a big deal, indeed. As said, you don't have to.

Anyway, I would argue it is better because of some subtile reasons:
- Less code to review. I needed to see if the code at `deleteCacheKeys` is correct (it's always possible to wrongly copy&paste) and that costed me a little bit of cognitive load. While using an already stablished util function is a sign to me as reviewer: "ok, you don't have to look at it, it will work".
- Code convention. It is better to stick to a convention than to have different solutions for each script. It will make to future developers harder to see in each migration a different way of doing the cache.
- Better developer experience. Once you get used to the util object, you will think it is simpler to import it and use it than copy&pasting the code at every new migration that deals with cache.

2024-04-09 20:51 UTC, merged